apiVersion: v1
kind: Service
metadata:
  name: nc-app
  labels:
    app: nc-app
spec:
  type: ClusterIP
  ports:
    - name: http-nc-app
      port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: nc-app
