apiVersion: apps/v1
kind: Deployment
metadata:
  name: nc-app
  labels:
    app: nc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nc-app
  template:
    metadata:
      labels:
        app: nc-app
    spec:
      containers:
      - image: yhaenggi/nc_app:latest
        imagePullPolicy: Always
        name: nc-app
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 25Mi
          limits:
            cpu: 1
            memory: 100Mi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
